blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, CreatePostView, DeletePostView,UpdatePostView


app_name = 'blog'
urlpatterns = [
    path('blog/', PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('blog/add/', CreatePostView.as_view(), name='post_add'),
    path('blog/<int:pk>/update', UpdatePostView.as_view(), name='update_post'),
    path('blog/<int:pk>/delete', DeletePostView.as_view(), name='post_delete')
]

myblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

from blog import views
from blog.admin import my_blog

urlpatterns = [
    path('admin/', my_blog.urls),
    path('', TemplateView.as_view(template_name='index.html')),
    path('', include('blog.urls', namespace='blog')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField
from django_ckeditor_5.fields import CKEditor5Field


# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        PUBLISHED = 'PB', 'Published'
        DRAFT = 'DF', 'Draft'

    title = models.CharField(max_length=200, help_text="Post title.")
    slug = models.SlugField(max_length=200, unique_for_date='publish',
                            help_text="The slug of the post.")
    snippet = models.CharField(max_length=250,default="No snippet", help_text="The snippet of the post.")
    body = CKEditor5Field('content', config_name='extends')
    publish = models.DateTimeField(default=timezone.now,
                                   help_text="The date and time the post was published.")
    created_date = models.DateTimeField(auto_now_add=True,
                                        help_text="The date and time the post was created.")
    updated_date = models.DateTimeField(auto_now=True, help_text="The date and time the post was edited.")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(default=Status.DRAFT, max_length=20,
                              choices=Status.choices)

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

blog/forms.py
from django_ckeditor_5.widgets import CKEditor5Widget

from .models import Post
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author', 'status', 'body', 'snippet')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'post title'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'body': CKEditor5Widget(
                  attrs={"class": "django_ckeditor_5"}, config_name="extends"),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'snippet': forms.TextInput(attrs={'class': 'form-control', 'rows': 10}),

        }

blog/views.py
from django.shortcuts import get_object_or_404, render

from .forms import PostForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Post


# Create your views here.
class PostListView(ListView):
    paginate_by = 4
    model = Post
    queryset = Post.objects.filter(status='PB')
    template_name = 'blog/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    return render(request, 'blog/detail.html', {'post': post})


class CreatePostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/add_post.html'
    success_url = reverse_lazy('blog:post_list')


class DeletePostView(DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('blog:post_list')


class UpdatePostView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/update_post.html'
    success_url = reverse_lazy('blog:post_list')

blog/templates/blog/add_post.html
{% extends 'blog/base.html' %}

{% block content %}

    <form method="post">
        {{ form.as_p }}
        {{ form.media }}
        {% csrf_token %}

        <button class="btn btn-secondary">Add Post</button>
    </form>


{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %}{% endblock %}</title>
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>


    <div class="m-2">
            <nav class="navbar navbar-expand-sm bg-body-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Glenn Pascal Mouhingou</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_add' %}">Add Post</a>
        </li>


      </ul>
    </div>
  </div>
</nav>
        <br>
    </div>
    <!-- End navbar -->
    <div id="content">
        {% block content %} {% endblock %}
    </div>

    <div id="sidebar">
        <h2>My Blog</h2>
        <p>This is my blog.</p>
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}


{% block content %}

    <h1>{% block title %} {{ post.title }} {% endblock %}</h1>
    <p>{{ post.body | safe }}</p>


{% endblock %}

blog/templates/blog/list.html
{% extends 'blog/base.html' %}


{% block content %}
    <h1>{% block title %}Welcome to my blog{% endblock %}</h1>
    {% for post in object_list %}

        <h3>
            <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
        </h3>
        <p class="date">Published: {{ post.publish }} by {{ post.author }}
              <a class="ms-3" href="{% url 'blog:update_post' post.id %}">Edit </a> |
            <a href="{% url 'blog:post_delete' post.id %}"> Delete</a>

        </p>

        {{ post.snippet | truncatewords:30 | linebreaks }}

    {% endfor %}

    {% include "blog/pagination.html" with page=page_obj %}




{% endblock %}

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="page-item" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>


            {% if page.has_next %}
                <a class="page-item" href="?page={{ page_obj.next_page_number }}">Next</a>
            {% endif %}
    </span>
</div>

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}


{% block content %}

    <form method="post">

    {% csrf_token %}
        <div>
       <h2> {{ post.title }}</h2>
    <br>
        <p>{{ post.body |truncatewords:20 }}</p>

    </div>

        <br>
    Are you sure you want to delete <strong>{{ post.title }} ?</strong><br>
        <br>
    <button  class="btn btn-secondary">Delete Post!</button>
        </form>


{% endblock %}

blog/templates/blog/update_post.html
{% extends 'blog/base.html' %}

{% block content %}

    <form method="post">
        {{ form.as_p }}
        {{ form.media }}
        {% csrf_token %}

        <button class="btn btn-secondary">Update Post</button>
    </form>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
</head>
<body>

    <div class="m-2">
            <nav class="navbar navbar-expand-sm bg-body-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Glenn Pascal Mouhingou</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>


      </ul>
    </div>
  </div>
</nav>
        
    </div>


    <br/>
    {% block content %}
    
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <h1>Hello world, welcome to my django website</h1>
{% endblock %}